### ISSUE TITLE
"An error occurred OpenDirectory:132: Failed to open directory /tinfoil/nsp. Error Code: 0x0000202"

### ISSUE THREAD

**Issue by dothackjhe** [XorTroll/Tinfoil#110]
So, I tried updating my SD card's contents based from the file from this link, only for Tinfoil to give me an error every time I access it's "NSP install" feature. Here's what the error says:

"An error occurred OpenDirectory:132: Failed to open directory /tinfoil/nsp. Error Code: 0x0000202"

My initial suspicion was that the micro-SD Card got corrupted somehow. But even after doing a check disk (chksdsk <drive letter>: /F) which supposedly fixes the issue, I'm still getting the issue. To double-check if the micro-SD card itself is the problem, I tried running an installed game and it works just fine.

**Comment by XorTroll** [comment]
Ok
