### ISSUE TITLE
Attempted to install game via USB, stuck at 99%

### ISSUE THREAD

**Issue by GuyInDogSuit** [XorTroll/Tinfoil#70]
The first attempt to install worked for me, but on this one it got to 99% and just sat there. It's been over 10 minutes now. What do I do?

**Comment by ThatNerdyPikachu** [comment]
Hm, that's weird.
Try rebuilding Tinfoil and rebooting the Switch (``make clean && make -j``)

**Comment by GuyInDogSuit** [comment]
I didn't build from source, I got it from the nightlies.

Also, I have no idea how to compile anything.

**Comment by Lorenzooone** [comment]
It's an issue with the nightly and version 5.1.0. Updated to 6.0.0 and it doesn't do it anymore.

**Comment by satelliteseeker** [comment]
Fix for 5.x is now available:
https://github.com/satelliteseeker/Tinfoil/releases/tag/v0.2.1-USB-fix

**Comment by GuyInDogSuit** [comment]
Thank you guys!
