### ISSUE TITLE
Usb install fails with some nsp

### ISSUE THREAD

**Issue by Paffo** [XorTroll/Tinfoil#72]
Hello,
first of all the new usb install is a fantastic feature, i get 24MB/s compared to the 2MB/s i was getting via network.

Anyway, installing few NSP it kept failing at one of them (The Legend of Zelda Breath of the Wild [01007ef00011e800][v720896].nsp)

i thought the nsp was damanged so i redownloaded it, but it kept failing.
i tried installing it via network and it worked flawlessly.

The fail consisted simply in the switch "fatal error press power button to reboot"

**Comment by XorTroll** [comment]
Usb support is still wip.
