### ISSUE TITLE
error message while network installation

### ISSUE THREAD

**Issue by Zboubinou** [XorTroll/Tinfoil#75]
Hi,
when i do a network installation it install correctely but the script always print this error (like every second) : 

>  Exception happened during processing of request from ('192.168.137.55', 13710)
> Traceback (most recent call last):
>   File "C:\Users\MyName\AppData\Local\Programs\Python\Python37-32\lib\socketserver.py", line 313, in _handle_request_noblock
>     self.process_request(request, client_address)
>   File "C:\Users\MyName\AppData\Local\Programs\Python\Python37-32\lib\socketserver.py", line 344, in process_request
>     self.finish_request(request, client_address)
>   File "C:\Users\MyName\AppData\Local\Programs\Python\Python37-32\lib\socketserver.py", line 357, in finish_request
>     self.RequestHandlerClass(request, client_address, self)
>   File "C:\Users\MyName\AppData\Local\Programs\Python\Python37-32\lib\http\server.py", line 646, in __init__
>     super().__init__(*args, **kwargs)
>   File "C:\Users\MyName\AppData\Local\Programs\Python\Python37-32\lib\socketserver.py", line 717, in __init__
>     self.handle()
>   File "C:\Users\MyName\AppData\Local\Programs\Python\Python37-32\lib\http\server.py", line 426, in handle
>     self.handle_one_request()
>   File "C:\Users\MyName\AppData\Local\Programs\Python\Python37-32\lib\http\server.py", line 414, in handle_one_request
>     method()
>   File "C:\Users\MyName\AppData\Local\Programs\Python\Python37-32\lib\http\server.py", line 653, in do_GET
>     self.copyfile(f, self.wfile)
>   File "C:\Users\MyName\Downloads\Switch\FileZillaPortable\remote_install_pc.py", line 121, in copyfile
>     outfile.write(buf)
>   File "C:\Users\MyName\AppData\Local\Programs\Python\Python37-32\lib\socketserver.py", line 796, in write
>     self._sock.sendall(b)
> ConnectionResetError: [WinError 10054] Une connexion existante a dû être fermée par l’hôte distant

Do you know what this is ? Great work otherwise

**Comment by ThatNerdyPikachu** [comment]
> ``ConnectionResetError: [WinError 10054] Une connexion existante a dû être fermée par l’hôte distant``

Mind translating this?

**Comment by LittleWhite-tb** [comment]
This is:
> An existing connection was forcibly closed by the remote host

**Comment by Zboubinou** [comment]
Thx
