### ISSUE TITLE
error with usb installation

### ISSUE THREAD

**Issue by Zboubinou** [XorTroll/Tinfoil#77]
Hi,
i'm trying to use the usb installation tool. I'm on Windows so i installed Pyusb and the driver with ziadig. Switch is ready, waiting for header but python script give me this : 

> Traceback (most recent call last):
> File "C:\Users\MyName\Downloads\tinfoil-267ef5b\tools\usb_install_pc.py", line 134, in <module>
> dev = usb.core.find(idVendor=0x057E, idProduct=0x3000)
> File "C:\Users\MyName\AppData\Local\Programs\Python\Python37-32\lib\site-packages\usb\core.py", line 1263, in find
> raise NoBackendError('No backend available')
> usb.core.NoBackendError: No backend available

Any idea ?

**Comment by Lorenzooone** [comment]
Go to "C:\Users\MyName\AppData\Local\Programs\Python\Python37-32\lib\site-packages\libusb\_platform\_windows" and copy the file named libusb-1.0.dll from the folder of your Python installation's architecture (x64 or x86) and put it in the same folder as the python script.

**Comment by Zboubinou** [comment]
Work like a charm, thw !
