### ISSUE TITLE
Plz add support for SXOS usbhdd://

### ISSUE THREAD

**Issue by esmith13** [XorTroll/Tinfoil#83]
Plz add support for SXOS usbhdd:// path as a source directory to find .nsp files to install.
Intended use would be to keep .xci's on USB HDD but also be able to place nsp update files there that must be installed with tinfoil so the OS version bypass can be used which is unavailable in SXOS nsp installer.

Example: Starlink base game runs on OS 5.1.0, Day 1 update to the game requires OS 6.0. Would like to put both .xci and .nsp on external USB HDD and have tinfoil install the nsp update from there to prevent any need to power off switch and remove microSD (or use USB/Network transfer).

**Comment by aveao** [comment]
SXOS stole from Tinfoil, why would people want to add support for an SXOS specific feature?

**Comment by XorTroll** [comment]
I would really like to add usb support, but still is undocumented by switchbrew or reswitched, and we still don't know how it works
