### ISSUE TITLE
USB install UI with newlines causes problems.

### ISSUE THREAD

**Issue by gr3ger** [XorTroll/Tinfoil#84]
If an item has a name that wraps two lines, the arrow will still move only one line down when pressing down, meaning that any item after that that will be installed is actually the item one down from the currently selected.

Example

This will install nsp1.nsp
```
> Games/nsp1.nsp 
Games/asdsdkjashdkasjdhsadkjadh
asasdlkasl.nsp
Games/test.nsp
```

And this will install crap.nsp
```
Games/nsp1.nsp 
Games/asdsdkjashdkasjdhsadkjadh
asasdlkasl.nsp
> Games/test.nsp
Games/crap.nsp
```

And that is because this selection is apparently valid:
```
Games/nsp1.nsp 
Games/asdsdkjashdkasjdhsadkjadh
> asasdlkasl.nsp
Games/test.nsp
Games/crap.nsp
```

**Comment by XorTroll** [comment]
Yeah don't worry, that will be fixed with the new GUI version gets released.
