### ISSUE TITLE
USB install hangs on 0%

### ISSUE THREAD

**Issue by LittlestCube** [XorTroll/Tinfoil#91]
I am updated to the latest version this time, but when I try to install Lego City Undercover (6.45 GB) it starts the installation process but never gets past 0%.

`> Download Progress: 0/0 MB (0%) (0.00 MB/s)`

Did I miss a step or something? I am using FAT32 micro SDXC Card (which I thought wouldn't be a problem if I used USB install, and using ExFAT to run homebrew doesn't work for me) and other games install and run fine.

EDIT: I moved the nsp to the SDXC Card and trying to installing normally I get:

`Failed to install NSP!`
`OpenFileSystemWithId:101: Failed to open file system with id: @Sdcard://tinfoil/nsp/LEGOCITY.nsp/*giantkey*.cnmt.nca. Error code: 0x00177a002`

**Comment by n0n0x** [comment]
> Did I miss a step or something? I am using FAT32 micro SDXC Card (which I thought wouldn't be a problem if I used USB install, and using ExFAT to run homebrew doesn't work for me) and other games install and run fine.

> EDIT: I moved the nsp to the SDXC Card and trying to installing normally I get:

> Failed to install NSP!
OpenFileSystemWithId:101: Failed to open file system with id: @Sdcard://tinfoil/nsp/LEGOCITY.nsp/*giantkey*.cnmt.nca. Error code: 0x00177a002

About this, FAT32 only supports files up to 2GB if I remember correctly (maybe 4GB), so if you moved a 6.5GB NSP to a FAT32 sd card, file would be corrupted for sure. (check size)


> I am updated to the latest version this time, but when I try to install Lego City Undercover (6.45 GB) it starts the installation process but never gets past 0%.

> Download Progress: 0/0 MB (0%) (0.00 MB/s)

Have you tried installing something smaller? like a small update or DLC? Just to check if it is working properly for you and it is not a setup issue

**Comment by LittlestCube** [comment]
> About this, FAT32 only supports files up to 2GB if I remember correctly (maybe 4GB), so if you moved a 6.5GB NSP to a FAT32 sd card, file would be corrupted for sure. (check size)

Forgot to mention that I found a way to get homebrew to work on ExFAT micro SD Card and then moved the 6 GB nsp.

> Have you tried installing something smaller? like a small update or DLC? Just to check if it is working properly for you and it is not a setup issue

Yes, and I believe this error was actually because the Lego City NSP was corrupted the same way as the OP in #87. I now do not believe this was an error with tinfoil.
