### ISSUE TITLE
Tinfoil crashes on 4.0.1 at launch

### ISSUE THREAD

**Issue by hax4dazy** [XorTroll/Tinfoil#97]
Hey,

I have no clue what i did but i got tinfoil to crash every time i try to open it.
My fw version is 4.0.1 i am running atmosphere cfw and the sd files where taken from [sd files.com](https://www.sdsetup.com/console?switch)

I think it got ***** up by playerNX because i have had this problem before i did fix it somehow...

**Comment by n0n0x** [comment]
It must be because of issue #93 download latest version form here: https://bsnx.lavatech.top/tinfoil/ and it should work

**Comment by hax4dazy** [comment]
Erm. Somehow it worked. Gonna update tomGER about it.
